export const payTypes = [
  { label: 'Карт', value: 'Карт' },
  { label: 'Дансаар', value: 'Дансаар' },
  { label: 'QPay', value: 'QPay' },
  { label: 'Mchat', value: 'Mchat' },
  { label: 'Бусад', value: 'Бусад' },
];

export const payShops = [
  { label: 'Shop1', value: 'Shop1', address: '15th street', qty: 2 },
  { label: 'Shop name 2', value: 'Shop2', address: '17th street', qty: 1 },
  { label: 'Shop name sub shop 3', value: 'Shop3', address: '25th street', qty: 1 },
  { label: 'Shop4', value: 'Shop4', address: '25th street', qty: 1 },
  { label: 'Shop5', value: 'Shop5', address: '25th street', qty: 1 },
  { label: 'Shop6', value: 'Shop6', address: '25th street', qty: 1 },
  { label: 'Shop7', value: 'Shop7', address: '25th street', qty: 1 },
  { label: 'Shop8', value: 'Shop8', address: '25th street', qty: 1 },
  { label: 'Shop9', value: 'Shop9', address: '25th street', qty: 1 },
];

export const colors = [
  '#e0e0e0',
  '#f44336',
  '#e91e63',
  '#ff9800',
  '#cddc39',
  '#4caf50',
  '#2196f3',
  '#9c27b0'
];

export const posTypes = [
  { value: "Windows", label: "Windows" },
  { value: "Android", label: "Android" },
  { value: "iOS", label: "iOS" }
];

export const posList = [
  { label: 'Бүх борлуулалтыг харах', value: 'posViewReceipt', checked: false },
  { label: 'Хөнгөлөлт ашиглах', value: 'posDiscount', checked: false },
  { label: 'Борлуулалт болон татвар өөрчлөх', value: 'posChangeSalesTaxes', checked: false },
  { label: 'Буцаалт авах', value: 'posReturn', checked: false },
  { label: 'Бүх нээлттэй захиалгыг удирдах', value: 'posManageTicket', checked: false },
  { label: 'Нээлттэй захиалгыг хүчингүй болгох', value: 'posVoidTicket', checked: false },
  { label: 'Ээлжийн тайлан харах', value: 'posViewShiftReport', checked: false },
  { label: 'Мөнгөний шургуулга нээх', value: 'posOpenCashDrawer', checked: false },
  { label: 'Баримт дахин хэвлэх', value: 'posReprintReceipt', checked: false },
  { label: 'Бараа бүртгэх', value: 'posManageItems', checked: false },
  { label: 'Тохиргоо өөрчлөх', value: 'posChangeSettings', checked: false },
  { label: 'Чатад хандах', value: 'posChat', checked: false },
  { label: 'Чатад хариу өгөх', value: 'posLiveChatSuport', checked: false },
];

export const webList = [
  { label: 'Борлуулалтын тайлан харах', value: 'webViewSalesReport', checked: false },
  { label: 'Бараа бүртгэх', value: 'webManageItem', checked: false },
  { label: 'Барааны үлдэгдэл харах', value: 'webViewItemBalance', checked: false },
  { label: 'Барааны орлого авах', value: 'webIsReceipt', checked: false },
  { label: 'Барааны хөдөлгөөн хийх', value: 'webIsTransfer', checked: false },
  { label: 'Барааны орлого зарлага хийх', value: 'webIsAdjust', checked: false },
  { label: 'Барааны тооллого хийх', value: 'webIsPicount', checked: false },
  { label: 'Барааны багцлалт хийх', value: 'webIsAssembly', checked: false },
  { label: 'Ажилтан бүртгэх', value: 'webManageEmployy', checked: false },
  { label: 'Харилцагч бүртгэх', value: 'webManageCustomer', checked: false },
  { label: 'Цаг захиалга бүртгэх', value: 'webAppointment', checked: false },
  { label: 'Санхүүгийн модуль ашиглах', value: 'webFinance', checked: false },
  { label: 'Тохиргоо өөрчлөх', value: 'webEditSettings', checked: false },
  { label: 'Төлбөрийн төрөл бүртгэх', value: 'webManagePaymentType', checked: false },
  { label: 'Лояалти үүсгэх', value: 'webManageLoyalty', checked: false },
  { label: 'Салбар бүртгэх', value: 'webManageSite', checked: false },
  { label: 'ПОС бүртгэх', value: 'webManagePos', checked: false },
];

export const timeList = [
  '00:00', '01:00', '02:00', '03:00', '04:00', '05:00', '06:00', '07:00', '08:00', '09:00',
  '10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00',
  '20:00', '21:00', '22:00', '23:00'
];
export const chartTypes = [
  { label: 'Line', value: 'line' },
  { label: 'Bar', value: 'bar' },
  { label: 'Pie', value: 'pie' },
];

export const limitList = [
  { value: 0, label: 'Нас харгалзахгүй' },
  { value: 16, label: '16 дээш ' },
  { value: 18, label: '18 дээш ' },
  { value: 21, label: '21 дээш ' },
]

export const graphList = [
  { value: true, label: 'Bar' },
  { value: false, label: 'Area' },
];

export const graphList1 = [
  { value: 'bar', label: 'Bar' },
  { value: 'line', label: 'Line' },
  { value: 'pie', label: 'Pie' },
];

export const zipTypes = [
  'application/x-freearc',
  'application/x-bzip',
  'application/x-bzip2',
  'application/gzip',
  'application/vnd.rar',
  'application/x-tar',
  'application/zip',
  'application/x-7z-compressed',
  'application/x-zip-compressed',
  'zip'
];

export const cityList = [
  { label: 'Багануур дүүрэг', value: 'Багануур дүүрэг', districtCode: '27', lan : 47.79295380535324, lng : 108.3875424635527,city : true},
  { label: 'Багахангай дүүрэг', value: 'Багахангай дүүрэг', districtCode: '28',  lan : 47.3564726734967, lng : 107.49710563516459, city : true},
  { label: 'Баянгол дүүрэг', value: 'Баянгол дүүрэг', districtCode: '26', lan : 47.91068290030032, lng : 106.85903691707063, city : true },
  { label: 'Баянзүрх дүүрэг', value: 'Баянзүрх дүүрэг', districtCode: '24', lan : 47.918612228335355, lng : 106.97828572460108, city : true },
  { label: 'Налайх дүүрэг', value: 'Налайх дүүрэг', districtCode: '29', lan :47.81117213649934 , lng : 107.42942593610115, city : true  },
  { label: 'Сонгинохайрхан дүүрэг', value: 'Сонгинохайрхан дүүрэг', districtCode: '34', lan : 47.93327772576724, lng : 106.80559007100574, city : true  },
  { label: 'Сүхбаатар дүүрэг', value: 'Сүхбаатар дүүрэг', districtCode: '25', lan : 48.06262925861685, lng : 106.91570856319267, city : true},
  { label: 'Хан-Уул дүүрэг', value: 'Хан-Уул дүүрэг', districtCode: '23', lan : 47.871496059736145, lng : 106.82521021013885, city : true },
  { label: 'Чингэлтэй дүүрэг', value: 'Чингэлтэй дүүрэг', districtCode: '35', lan :48.03078977359782 , lng :106.87786142932592, city : true },
  { label: 'Архангай аймаг', value: 'Архангай аймаг', districtCode: '01', lan : 47.47011437157903, lng : 101.47579513075361},
  { label: 'Баян-Өлгий аймаг', value: 'Баян-Өлгий аймаг', districtCode: '02', lan : 48.96699421567877, lng : 89.96325947840711 },
  { label: 'Баянхонгор аймаг', value: 'Баянхонгор аймаг', districtCode: '03', lan : 44.56427563774115, lng : 99.23261077870883},
  { label: 'Булган аймаг', value: 'Булган аймаг', districtCode: '04', lan : 48.85392623326567, lng : 103.4680655219553},
  { label: 'Говь-Алтай аймаг', value: 'Говь-Алтай аймаг', districtCode: '05', lan : 46.368483023500154, lng : 96.26448376458988 },
  { label: 'Говьсүмбэр аймаг', value: 'Говьсүмбэр аймаг', districtCode: '32', lan : 46.3548307737369, lng : 108.40592663952658},
  { label: 'Дархан-Уул аймаг', value: 'Дархан-Уул аймаг', districtCode: '19', lan : 49.455274469060896, lng : 106.0258688883597},
  { label: 'Дорноговь аймаг', value: 'Дорноговь аймаг', districtCode: '06', lan : 44.894491570424215, lng : 110.13425394247345},
  { label: 'Дорнод аймаг', value: 'Дорнод аймаг', districtCode: '07', lan : 48.10290041726158, lng : 114.53130872256011},
  { label: 'Дундговь аймаг', value: 'Дундговь аймаг', districtCode: '08', lan : 45.787668753119874, lng : 107.2554685712039},
  { label: 'Завхан аймаг', value: 'Завхан аймаг', districtCode: '09', lan : 47.72564069980576, lng : 96.84662484541978},
  { label: 'Орхон аймаг', value: 'Орхон аймаг', districtCode: '20', lan : 49.055519142692376, lng : 104.08450772304846},
  { label: 'Өвөрхангай аймаг', value: 'Өвөрхангай аймаг', districtCode: '10', lan : 46.27830486973693, lng : 102.79741348859746},
  { label: 'Өмнөговь аймаг', value: 'Өмнөговь аймаг', districtCode: '11', lan : 43.554639098295716, lng : 104.3697309526747},
  { label: 'Сүхбаатар аймаг', value: 'Сүхбаатар аймаг', districtCode: '12', lan : 46.66535750425093, lng : 113.2899121748773},
  { label: 'Сэлэнгэ аймаг', value: 'Сэлэнгэ аймаг', districtCode: '13', lan : 49.09092549495758, lng : 105.5606122479413},
  { label: 'Төв аймаг', value: 'Төв аймаг', districtCode: '14', lan : 47.701628733460424, lng : 106.95453583016571},
  { label: 'Увс аймаг', value: 'Увс аймаг', districtCode: '15', lan : 49.991594200189446, lng : 92.05309886537695},
  { label: 'Ховд аймаг', value: 'Ховд аймаг', districtCode: '16', lan : 47.97965244974589, lng : 91.63487776547134},
  { label: 'Хөвсгөл аймаг', value: 'Хөвсгөл аймаг', districtCode: '17', lan : 49.64407423742748, lng : 100.18180227955075},
  { label: 'Хэнтий аймаг', value: 'Хэнтий аймаг', districtCode: '18', lan : 47.31930210285031, lng : 110.65747530095545},
];
export const districtList = [
  { parent: 'Багануур дүүрэг,Багахангай дүүрэг,Баянгол дүүрэг,Баянзүрх дүүрэг,Налайх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '1-р хороо', value: '1-р хороо' },
  { parent: 'Багануур дүүрэг,Багахангай дүүрэг,Баянгол дүүрэг,Баянзүрх дүүрэг,Налайх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '2-р хороо', value: '2-р хороо' },
  { parent: 'Багануур дүүрэг,Багахангай дүүрэг,Баянгол дүүрэг,Баянзүрх дүүрэг,Налайх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '3-р хороо', value: '3-р хороо' },
  { parent: 'Багануур дүүрэг,Багахангай дүүрэг,Баянгол дүүрэг,Баянзүрх дүүрэг,Налайх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '4-р хороо', value: '4-р хороо' },
  { parent: 'Багануур дүүрэг,Багахангай дүүрэг,Баянгол дүүрэг,Баянзүрх дүүрэг,Налайх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '5-р хороо', value: '5-р хороо' },

  { parent: 'Багахангай дүүрэг,Баянгол дүүрэг,Баянзүрх дүүрэг,Налайх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '6-р хороо', value: '6-р хороо' },
  { parent: 'Багахангай дүүрэг,Баянгол дүүрэг,Баянзүрх дүүрэг,Налайх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '7-р хороо', value: '7-р хороо' },
  { parent: 'Багахангай дүүрэг,Баянгол дүүрэг,Баянзүрх дүүрэг,Налайх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '8-р хороо', value: '8-р хороо' },
  
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '9-р хороо', value: '9-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '10-р хороо', value: '10-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '11-р хороо', value: '11-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '12-р хороо', value: '12-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '13-р хороо', value: '13-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '14-р хороо', value: '14-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '15-р хороо', value: '15-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '16-р хороо', value: '16-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '17-р хороо', value: '17-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '18-р хороо', value: '18-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг,Чингэлтэй дүүрэг', label: '19-р хороо', value: '19-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг,Сүхбаатар дүүрэг,Хан-Уул дүүрэг', label: '20-р хороо', value: '20-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг,Хан-Уул дүүрэг', label: '21-р хороо', value: '21-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг', label: '22-р хороо', value: '22-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг', label: '23-р хороо', value: '23-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг', label: '24-р хороо', value: '24-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг', label: '25-р хороо', value: '25-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг', label: '26-р хороо', value: '26-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг', label: '27-р хороо', value: '27-р хороо' },
  { parent: 'Баянгол дүүрэг,Баянзүрх дүүрэг,Сонгинохайрхан дүүрэг', label: '28-р хороо', value: '28-р хороо' },
  { parent: 'Баянгол дүүрэг,Сонгинохайрхан дүүрэг', label: '29-р хороо', value: '29-р хороо' },
  { parent: 'Баянгол дүүрэг,Сонгинохайрхан дүүрэг', label: '30-р хороо', value: '30-р хороо' },
  { parent: 'Баянгол дүүрэг,Сонгинохайрхан дүүрэг', label: '31-р хороо', value: '31-р хороо' },
  { parent: 'Баянгол дүүрэг,Сонгинохайрхан дүүрэг', label: '32-р хороо', value: '32-р хороо' },
  { parent: 'Баянгол дүүрэг,Сонгинохайрхан дүүрэг', label: '33-р хороо', value: '33-р хороо' },

  { parent: 'Сонгинохайрхан дүүрэг', label: '34-р хороо', value: '34-р хороо' },
  { parent: 'Сонгинохайрхан дүүрэг', label: '35-р хороо', value: '35-р хороо' },
  { parent: 'Сонгинохайрхан дүүрэг', label: '36-р хороо', value: '36-р хороо' },
  { parent: 'Сонгинохайрхан дүүрэг', label: '37-р хороо', value: '37-р хороо' },
  { parent: 'Сонгинохайрхан дүүрэг', label: '38-р хороо', value: '38-р хороо' },
  { parent: 'Сонгинохайрхан дүүрэг', label: '39-р хороо', value: '39-р хороо' },
  { parent: 'Сонгинохайрхан дүүрэг', label: '40-р хороо', value: '40-р хороо' },
  { parent: 'Сонгинохайрхан дүүрэг', label: '41-р хороо', value: '41-р хороо' },
  { parent: 'Сонгинохайрхан дүүрэг', label: '42-р хороо', value: '42-р хороо' },
  { parent: 'Сонгинохайрхан дүүрэг', label: '43-р хороо', value: '33-р хороо' },

  { parent: 'Архангай аймаг', label: 'Цэцэрлэг', value: 'Цэцэрлэг' },
  { parent: 'Архангай аймаг', label: 'Батцэнгэл', value: 'Батцэнгэл' },
  { parent: 'Архангай аймаг', label: 'Булган', value: 'Булган' },
  { parent: 'Архангай аймаг', label: 'Жаргалант', value: 'Жаргалант' },
  { parent: 'Архангай аймаг', label: 'Ихтамир', value: 'Ихтамир' },
  { parent: 'Архангай аймаг', label: 'Өгийнуур', value: 'Өгийнуур' },
  { parent: 'Архангай аймаг', label: 'Өлзийт', value: 'Өлзийт' },
  { parent: 'Архангай аймаг', label: 'Өндөр-Улаан', value: 'Өндөр-Улаан' },
  { parent: 'Архангай аймаг', label: 'Тариат', value: 'Тариат' },
  { parent: 'Архангай аймаг', label: 'Төвшрүүлэх', value: 'Төвшрүүлэх' },
  { parent: 'Архангай аймаг', label: 'Хайрхан', value: 'Хайрхан' },
  { parent: 'Архангай аймаг', label: 'Хангай', value: 'Хангай' },
  { parent: 'Архангай аймаг', label: 'Хашаат', value: 'Хашаат' },
  { parent: 'Архангай аймаг', label: 'Хотонт', value: 'Хотонт' },
  { parent: 'Архангай аймаг', label: 'Цахир', value: 'Цахир' },
  { parent: 'Архангай аймаг', label: 'Цэнхэр', value: 'Цэнхэр' },
  { parent: 'Архангай аймаг', label: 'Чулуут', value: 'Чулуут' },
  { parent: 'Архангай аймаг', label: 'Эрдэнэбулган', value: 'Эрдэнэбулган' },
  { parent: 'Архангай аймаг', label: 'Эрдэнэмандал', value: 'Эрдэнэмандал' },

  { parent: 'Баян-Өлгий аймаг', label: 'Өлгий', value: 'Өлгий' },
  { parent: 'Баян-Өлгий аймаг', label: 'Алтай', value: 'Алтай' },
  { parent: 'Баян-Өлгий аймаг', label: 'Алтанцөгц', value: 'Алтанцөгц' },
  { parent: 'Баян-Өлгий аймаг', label: 'Баяннуур', value: 'Баяннуур' },
  { parent: 'Баян-Өлгий аймаг', label: 'Бугат', value: 'Бугат' },
  { parent: 'Баян-Өлгий аймаг', label: 'Булган', value: 'Булган' },
  { parent: 'Баян-Өлгий аймаг', label: 'Буянт', value: 'Буянт' },
  { parent: 'Баян-Өлгий аймаг', label: 'Дэлүүн', value: 'Дэлүүн' },
  { parent: 'Баян-Өлгий аймаг', label: 'Ногооннуур', value: 'Ногооннуур' },
  { parent: 'Баян-Өлгий аймаг', label: 'Сагсай', value: 'Сагсай' },
  { parent: 'Баян-Өлгий аймаг', label: 'Толбо', value: 'Толбо' },
  { parent: 'Баян-Өлгий аймаг', label: 'Улаанхус', value: 'Улаанхус' },
  { parent: 'Баян-Өлгий аймаг', label: 'Цагааннуур', value: 'Цагааннуур' },
  { parent: 'Баян-Өлгий аймаг', label: 'Цэнгэл', value: 'Цэнгэл' },

  { parent: 'Баянхонгор аймаг', label: 'Баянхонгор', value: 'Баянхонгор' },
  { parent: 'Баянхонгор аймаг', label: 'Баацагаан', value: 'Баацагаан' },
  { parent: 'Баянхонгор аймаг', label: 'Баянбулаг', value: 'Баянбулаг' },
  { parent: 'Баянхонгор аймаг', label: 'Баянговь', value: 'Баянговь' },
  { parent: 'Баянхонгор аймаг', label: 'Баянлиг', value: 'Баянлиг' },
  { parent: 'Баянхонгор аймаг', label: 'Баян-Овоо', value: 'Баян-Овоо' },
  { parent: 'Баянхонгор аймаг', label: 'Баян-Өндөр', value: 'Баян-Өндөр' },
  { parent: 'Баянхонгор аймаг', label: 'Баянцагаан', value: 'Баянцагаан' },
  { parent: 'Баянхонгор аймаг', label: 'Богд', value: 'Богд' },
  { parent: 'Баянхонгор аймаг', label: 'Бөмбөгөр', value: 'Бөмбөгөр' },
  { parent: 'Баянхонгор аймаг', label: 'Бууцагаан', value: 'Бууцагаан' },
  { parent: 'Баянхонгор аймаг', label: 'Галуут', value: 'Галуут' },
  { parent: 'Баянхонгор аймаг', label: 'Гурванбулаг', value: 'Гурванбулаг' },
  { parent: 'Баянхонгор аймаг', label: 'Жаргалант', value: 'Жаргалант' },
  { parent: 'Баянхонгор аймаг', label: 'Жинст', value: 'Жинст' },
  { parent: 'Баянхонгор аймаг', label: 'Заг', value: 'Заг' },
  { parent: 'Баянхонгор аймаг', label: 'Өлзийт', value: 'Өлзийт' },
  { parent: 'Баянхонгор аймаг', label: 'Хүрээмарал', value: 'Хүрээмарал' },
  { parent: 'Баянхонгор аймаг', label: 'Шинэжинст', value: 'Шинэжинст' },
  { parent: 'Баянхонгор аймаг', label: 'Эрдэнэцогт', value: 'Эрдэнэцогт' },

  { parent: 'Булган аймаг', label: 'Баян-Агт', value: 'Баян-Агт' },
  { parent: 'Булган аймаг', label: 'Баяннуур', value: 'Баяннуур' },
  { parent: 'Булган аймаг', label: 'Бугат', value: 'Бугат' },
  { parent: 'Булган аймаг', label: 'Бүрэгхангай', value: 'Бүрэгхангай' },
  { parent: 'Булган аймаг', label: 'Гурванбулаг', value: 'Гурванбулаг' },
  { parent: 'Булган аймаг', label: 'Дашинчилэн', value: 'Дашинчилэн' },
  { parent: 'Булган аймаг', label: 'Могод', value: 'Могод' },
  { parent: 'Булган аймаг', label: 'Орхон', value: 'Орхон' },
  { parent: 'Булган аймаг', label: 'Рашаант', value: 'Рашаант' },
  { parent: 'Булган аймаг', label: 'Сайхан', value: 'Сайхан' },
  { parent: 'Булган аймаг', label: 'Сэлэнгэ', value: 'Сэлэнгэ' },
  { parent: 'Булган аймаг', label: 'Тэшиг', value: 'Тэшиг' },
  { parent: 'Булган аймаг', label: 'Хангал', value: 'Хангал' },
  { parent: 'Булган аймаг', label: 'Хишиг-Өндөр', value: 'Хишиг-Өндөр' },
  { parent: 'Булган аймаг', label: 'Хутаг-Өндөр<', value: 'Хутаг-Өндөр<' },

  { parent: 'Говь-Алтай аймаг', label: 'Алтай', value: 'Алтай' },
  { parent: 'Говь-Алтай аймаг', label: 'Баян-Уул', value: 'Баян-Уул' },
  { parent: 'Говь-Алтай аймаг', label: 'Бигэр', value: 'Бигэр' },
  { parent: 'Говь-Алтай аймаг', label: 'Бугат', value: 'Бугат' },
  { parent: 'Говь-Алтай аймаг', label: 'Дарви', value: 'Дарви' },
  { parent: 'Говь-Алтай аймаг', label: 'Дэлгэр', value: 'Дэлгэр' },
  { parent: 'Говь-Алтай аймаг', label: 'Жаргалан', value: 'Жаргалан' },
  { parent: 'Говь-Алтай аймаг', label: 'Есөнбулаг', value: 'Есөнбулаг' },
  { parent: 'Говь-Алтай аймаг', label: 'Тайшир', value: 'Тайшир' },
  { parent: 'Говь-Алтай аймаг', label: 'Тонхил', value: 'Тонхил' },
  { parent: 'Говь-Алтай аймаг', label: 'Төгрөг', value: 'Төгрөг' },
  { parent: 'Говь-Алтай аймаг', label: 'Халиун', value: 'Халиун' },
  { parent: 'Говь-Алтай аймаг', label: 'Хөхморьт', value: 'Хөхморьт' },
  { parent: 'Говь-Алтай аймаг', label: 'Цогт', value: 'Цогт' },
  { parent: 'Говь-Алтай аймаг', label: 'Цээл', value: 'Цээл' },
  { parent: 'Говь-Алтай аймаг', label: 'Чандмань', value: 'Чандмань' },
  { parent: 'Говь-Алтай аймаг', label: 'Шарга', value: 'Шарга' },
  { parent: 'Говь-Алтай аймаг', label: 'Эрдэнэ', value: 'Эрдэнэ' },

  { parent: 'Говьсүмбэр аймаг', label: 'Чойр', value: 'Чойр' },
  { parent: 'Говьсүмбэр аймаг', label: 'Сүмбэр', value: 'Сүмбэр' },
  { parent: 'Говьсүмбэр аймаг', label: 'Баянтал', value: 'Баянтал' },
  { parent: 'Говьсүмбэр аймаг', label: 'Шивээговь', value: 'Шивээговь' },

  { parent: 'Дархан-Уул аймаг', label: 'Дархан', value: 'Дархан' },
  { parent: 'Дархан-Уул аймаг', label: 'Орхон', value: 'Орхон' },
  { parent: 'Дархан-Уул аймаг', label: 'Хонгор', value: 'Хонгор' },
  { parent: 'Дархан-Уул аймаг', label: 'Шарын гол', value: 'Шарын гол' },

  { parent: 'Дорноговь аймаг', label: 'Сайншанд', value: 'Сайншанд' },
  { parent: 'Дорноговь аймаг', label: 'Айраг', value: 'Айраг' },
  { parent: 'Дорноговь аймаг', label: 'Алтанширээ', value: 'Алтанширээ' },
  { parent: 'Дорноговь аймаг', label: 'Даланжаргалан', value: 'Даланжаргалан' },
  { parent: 'Дорноговь аймаг', label: 'Дэлгэрэх', value: 'Дэлгэрэх' },
  { parent: 'Дорноговь аймаг', label: 'Замын-Үүд', value: 'Замын-Үүд' },
  { parent: 'Дорноговь аймаг', label: 'Иххэт', value: 'Иххэт' },
  { parent: 'Дорноговь аймаг', label: 'Мандах', value: 'Мандах' },
  { parent: 'Дорноговь аймаг', label: 'Өргөн', value: 'Өргөн' },
  { parent: 'Дорноговь аймаг', label: 'Сайхандулаан', value: 'Сайхандулаан' },
  { parent: 'Дорноговь аймаг', label: 'Улаанбадрах', value: 'Улаанбадрах' },
  { parent: 'Дорноговь аймаг', label: 'Хатанбулаг', value: 'Хатанбулаг' },
  { parent: 'Дорноговь аймаг', label: 'Хөвсгөл', value: 'Хөвсгөл' },
  { parent: 'Дорноговь аймаг', label: 'Эрдэнэ', value: 'Эрдэнэ' },

  { parent: 'Дорнод аймаг', label: 'Чойбалсан', value: 'Чойбалсан' },
  { parent: 'Дорнод аймаг', label: 'Баяндун', value: 'Баяндун' },
  { parent: 'Дорнод аймаг', label: 'Баянтүмэн', value: 'Баянтүмэн' },
  { parent: 'Дорнод аймаг', label: 'Баян-Уул', value: 'Баян-Уул' },
  { parent: 'Дорнод аймаг', label: 'Булган', value: 'Булган' },
  { parent: 'Дорнод аймаг', label: 'Гурванзагал', value: 'Гурванзагал' },
  { parent: 'Дорнод аймаг', label: 'Дашбалбар', value: 'Дашбалбар' },
  { parent: 'Дорнод аймаг', label: 'Матад', value: 'Матад' },
  { parent: 'Дорнод аймаг', label: 'Сэргэлэн', value: 'Сэргэлэн' },
  { parent: 'Дорнод аймаг', label: 'Халхгол', value: 'Халхгол' },
  { parent: 'Дорнод аймаг', label: 'Хөлөнбуйр', value: 'Хөлөнбуйр' },
  { parent: 'Дорнод аймаг', label: 'Хэрлэн', value: 'Хэрлэн' },
  { parent: 'Дорнод аймаг', label: 'Цагаан-Овоо', value: 'Цагаан-Овоо' },
  { parent: 'Дорнод аймаг', label: 'Чулуунхороот', value: 'Чулуунхороот' },

  { parent: 'Дундговь аймаг', label: 'Мандалговь', value: 'Мандалговь' },
  { parent: 'Дундговь аймаг', label: 'Адаацаг', value: 'Адаацаг' },
  { parent: 'Дундговь аймаг', label: 'Баянжаргалан', value: 'Баянжаргалан' },
  { parent: 'Дундговь аймаг', label: 'Говь-Угтаал', value: 'Говь-Угтаал' },
  { parent: 'Дундговь аймаг', label: 'Гурвансайхан', value: 'Гурвансайхан' },
  { parent: 'Дундговь аймаг', label: 'Дэлгэрхангай', value: 'Дэлгэрхангай' },
  { parent: 'Дундговь аймаг', label: 'Дэлгэрцогт', value: 'Дэлгэрцогт' },
  { parent: 'Дундговь аймаг', label: 'Дэрэн', value: 'Дэрэн' },
  { parent: 'Дундговь аймаг', label: 'Луус', value: 'Луус' },
  { parent: 'Дундговь аймаг', label: 'Өлзийт', value: 'Өлзийт' },
  { parent: 'Дундговь аймаг', label: 'Өндөршил', value: 'Өндөршил' },
  { parent: 'Дундговь аймаг', label: 'Сайнцагаан', value: 'Сайнцагаан' },
  { parent: 'Дундговь аймаг', label: 'Сайхан-Овоо', value: 'Сайхан-Овоо' },
  { parent: 'Дундговь аймаг', label: 'Хулд', value: 'Хулд' },
  { parent: 'Дундговь аймаг', label: 'Цагаандэлгэр', value: 'Цагаандэлгэр' },
  { parent: 'Дундговь аймаг', label: 'Эрдэнэдалай', value: 'Эрдэнэдалай' },

  { parent: 'Завхан аймаг', label: 'Улиастай', value: 'Улиастай' },
  { parent: 'Завхан аймаг', label: 'Алдархаан', value: 'Алдархаан' },
  { parent: 'Завхан аймаг', label: 'Асгат', value: 'Асгат' },
  { parent: 'Завхан аймаг', label: 'Баянтэс', value: 'Баянтэс' },
  { parent: 'Завхан аймаг', label: 'Баянхайрхан', value: 'Баянхайрхан' },
  { parent: 'Завхан аймаг', label: 'Дөрвөлжин', value: 'Дөрвөлжин' },
  { parent: 'Завхан аймаг', label: 'Завханмандал', value: 'Завханмандал' },
  { parent: 'Завхан аймаг', label: 'Идэр', value: 'Идэр' },
  { parent: 'Завхан аймаг', label: 'Их-Уул', value: 'Их-Уул' },
  { parent: 'Завхан аймаг', label: 'Нөмрөг', value: 'Нөмрөг' },
  { parent: 'Завхан аймаг', label: 'Отгон', value: 'Отгон' },
  { parent: 'Завхан аймаг', label: 'Сантмаргаз', value: 'Сантмаргаз' },
  { parent: 'Завхан аймаг', label: 'Сонгино', value: 'Сонгино' },
  { parent: 'Завхан аймаг', label: 'Тосонцэнгэл', value: 'Тосонцэнгэл' },
  { parent: 'Завхан аймаг', label: 'Түдэвтэй', value: 'Түдэвтэй' },
  { parent: 'Завхан аймаг', label: 'Тэлмэн', value: 'Тэлмэн' },
  { parent: 'Завхан аймаг', label: 'Тэс', value: 'Тэс' },
  { parent: 'Завхан аймаг', label: 'Ургамал', value: 'Ургамал' },
  { parent: 'Завхан аймаг', label: 'Цагаанхайрхан', value: 'Цагаанхайрхан' },
  { parent: 'Завхан аймаг', label: 'Цагаанчулуут', value: 'Цагаанчулуут' },
  { parent: 'Завхан аймаг', label: 'Цэцэн-Уул', value: 'Цэцэн-Уул' },
  { parent: 'Завхан аймаг', label: 'Шилүүстэй', value: 'Шилүүстэй' },
  { parent: 'Завхан аймаг', label: 'Эрдэнэхайрхан', value: 'Эрдэнэхайрхан' },
  { parent: 'Завхан аймаг', label: 'Яруу', value: 'Яруу' },

  { parent: 'Орхон аймаг', label: 'Эрдэнэт', value: 'Эрдэнэт' },
  { parent: 'Орхон аймаг', label: 'Баян-Өндөр', value: 'Баян-Өндөр' },
  { parent: 'Орхон аймаг', label: 'Жаргалант', value: 'Жаргалант' },

  { parent: 'Өвөрхангай аймаг', label: 'Арвайхээр', value: 'Арвайхээр' },
  { parent: 'Өвөрхангай аймаг', label: 'Баруунбаян-Улаан', value: 'Баруунбаян-Улаан' },
  { parent: 'Өвөрхангай аймаг', label: 'Бат-Өлзий', value: 'Бат-Өлзий' },
  { parent: 'Өвөрхангай аймаг', label: 'Баянгол', value: 'Баянгол' },
  { parent: 'Өвөрхангай аймаг', label: 'Баян-Өндөр', value: 'Баян-Өндөр' },
  { parent: 'Өвөрхангай аймаг', label: 'Богд', value: 'Богд' },
  { parent: 'Өвөрхангай аймаг', label: 'Бүрд', value: 'Бүрд' },
  { parent: 'Өвөрхангай аймаг', label: 'Гучин-Ус', value: 'Гучин-Ус' },
  { parent: 'Өвөрхангай аймаг', label: 'Есөнзүйл', value: 'Есөнзүйл' },
  { parent: 'Өвөрхангай аймаг', label: 'Зүүнбаян-Улаан', value: 'Зүүнбаян-Улаан' },
  { parent: 'Өвөрхангай аймаг', label: 'Нарийнтээл', value: 'Нарийнтээл' },
  { parent: 'Өвөрхангай аймаг', label: 'Өлзийт', value: 'Өлзийт' },
  { parent: 'Өвөрхангай аймаг', label: 'Сант', value: 'Сант' },
  { parent: 'Өвөрхангай аймаг', label: 'Тарагт', value: 'Тарагт' },
  { parent: 'Өвөрхангай аймаг', label: 'Төгрөг', value: 'Төгрөг' },
  { parent: 'Өвөрхангай аймаг', label: 'Уянга', value: 'Уянга' },
  { parent: 'Өвөрхангай аймаг', label: 'Хайрхандулаан', value: 'Хайрхандулаан' },
  { parent: 'Өвөрхангай аймаг', label: 'Хархорин', value: 'Хархорин' },
  { parent: 'Өвөрхангай аймаг', label: 'Хужирт', value: 'Хужирт' },

  { parent: 'Өмнөговь аймаг', label: 'Даланзадгад', value: 'Даланзадгад' },
  { parent: 'Өмнөговь аймаг', label: 'Баяндалай', value: 'Баяндалай' },
  { parent: 'Өмнөговь аймаг', label: 'Баян-Овоо', value: 'Баян-Овоо' },
  { parent: 'Өмнөговь аймаг', label: 'Булган', value: 'Булган' },
  { parent: 'Өмнөговь аймаг', label: 'Гурвантэс', value: 'Гурвантэс' },
  { parent: 'Өмнөговь аймаг', label: 'Мандал-Овоо', value: 'Мандал-Овоо' },
  { parent: 'Өмнөговь аймаг', label: 'Манлай', value: 'Манлай' },
  { parent: 'Өмнөговь аймаг', label: 'Ноён', value: 'Ноён' },
  { parent: 'Өмнөговь аймаг', label: 'Номгон', value: 'Номгон' },
  { parent: 'Өмнөговь аймаг', label: 'Сэврэй', value: 'Сэврэй' },
  { parent: 'Өмнөговь аймаг', label: 'Ханбогд', value: 'Ханбогд' },
  { parent: 'Өмнөговь аймаг', label: 'Ханхонгор', value: 'Ханхонгор' },
  { parent: 'Өмнөговь аймаг', label: 'Хүрмэн', value: 'Хүрмэн' },
  { parent: 'Өмнөговь аймаг', label: 'Цогт-Овоо', value: 'Цогт-Овоо' },
  { parent: 'Өмнөговь аймаг', label: 'Цогтцэций', value: 'Цогтцэций' },

  { parent: 'Сүхбаатар аймаг', label: 'Баруун-Урт', value: 'Баруун-Урт' },
  { parent: 'Сүхбаатар аймаг', label: 'Асгат', value: 'Асгат' },
  { parent: 'Сүхбаатар аймаг', label: 'Баяндэлгэр', value: 'Баяндэлгэр' },
  { parent: 'Сүхбаатар аймаг', label: 'Дарьганга', value: 'Дарьганга' },
  { parent: 'Сүхбаатар аймаг', label: 'Мөнххаан', value: 'Мөнххаан' },
  { parent: 'Сүхбаатар аймаг', label: 'Наран', value: 'Наран' },
  { parent: 'Сүхбаатар аймаг', label: 'Онгон', value: 'Онгон' },
  { parent: 'Сүхбаатар аймаг', label: 'Сүхбаатар', value: 'Сүхбаатар' },
  { parent: 'Сүхбаатар аймаг', label: 'Түвшинширээ', value: 'Түвшинширээ' },
  { parent: 'Сүхбаатар аймаг', label: 'Түмэнцогт', value: 'Түмэнцогт' },
  { parent: 'Сүхбаатар аймаг', label: 'Уулбаян', value: 'Уулбаян' },
  { parent: 'Сүхбаатар аймаг', label: 'Халзан', value: 'Халзан' },
  { parent: 'Сүхбаатар аймаг', label: 'Эрдэнэцагаан', value: 'Эрдэнэцагаан' },

  { parent: 'Сэлэнгэ аймаг', label: 'Сүхбаатар', value: 'Сүхбаатар' },
  { parent: 'Сэлэнгэ аймаг', label: 'Алтанбулаг', value: 'Алтанбулаг' },
  { parent: 'Сэлэнгэ аймаг', label: 'Баруунбүрэн', value: 'Баруунбүрэн' },
  { parent: 'Сэлэнгэ аймаг', label: 'Баянгол', value: 'Баянгол' },
  { parent: 'Сэлэнгэ аймаг', label: 'Ерөө', value: 'Ерөө' },
  { parent: 'Сэлэнгэ аймаг', label: 'Жавхлант', value: 'Жавхлант' },
  { parent: 'Сэлэнгэ аймаг', label: 'Зүүнбүрэн', value: 'Зүүнбүрэн' },
  { parent: 'Сэлэнгэ аймаг', label: 'Мандал', value: 'Мандал' },
  { parent: 'Сэлэнгэ аймаг', label: 'Орхон', value: 'Орхон' },
  { parent: 'Сэлэнгэ аймаг', label: 'Орхонтуул', value: 'Орхонтуул' },
  { parent: 'Сэлэнгэ аймаг', label: 'Сайхан', value: 'Сайхан' },
  { parent: 'Сэлэнгэ аймаг', label: 'Сант', value: 'Сант' },
  { parent: 'Сэлэнгэ аймаг', label: 'Түшиг', value: 'Түшиг' },
  { parent: 'Сэлэнгэ аймаг', label: 'Хушаат', value: 'Хушаат' },
  { parent: 'Сэлэнгэ аймаг', label: 'Хүдэр', value: 'Хүдэр' },
  { parent: 'Сэлэнгэ аймаг', label: 'Цагааннуур', value: 'Цагааннуур' },
  { parent: 'Сэлэнгэ аймаг', label: 'Шаамар', value: 'Шаамар' },

  { parent: 'Төв аймаг', label: 'Зуунмод', value: 'Зуунмод' },
  { parent: 'Төв аймаг', label: 'Алтанбулаг', value: 'Алтанбулаг' },
  { parent: 'Төв аймаг', label: 'Аргалант', value: 'Аргалант' },
  { parent: 'Төв аймаг', label: 'Архуст', value: 'Архуст' },
  { parent: 'Төв аймаг', label: 'Батсүмбэр', value: 'Батсүмбэр' },
  { parent: 'Төв аймаг', label: 'Баян', value: 'Баян' },
  { parent: 'Төв аймаг', label: 'Баяндэлгэр', value: 'Баяндэлгэр' },
  { parent: 'Төв аймаг', label: 'Баянжаргалан', value: 'Баянжаргалан' },
  { parent: 'Төв аймаг', label: 'Баян-Өнжүүл', value: 'Баян-Өнжүүл' },
  { parent: 'Төв аймаг', label: 'Баянхангай', value: 'Баянхангай' },
  { parent: 'Төв аймаг', label: 'Баянцагаан', value: 'Баянцагаан' },
  { parent: 'Төв аймаг', label: 'Баянцогт', value: 'Баянцогт' },
  { parent: 'Төв аймаг', label: 'Баянчандмань', value: 'Баянчандмань' },
  { parent: 'Төв аймаг', label: 'Борнуур', value: 'Борнуур' },
  { parent: 'Төв аймаг', label: 'Бүрэн', value: 'Бүрэн' },
  { parent: 'Төв аймаг', label: 'Дэлгэрхаан', value: 'Дэлгэрхаан' },
  { parent: 'Төв аймаг', label: 'Жаргалант', value: 'Жаргалант' },
  { parent: 'Төв аймаг', label: 'Заамар', value: 'Заамар' },
  { parent: 'Төв аймаг', label: 'Лүн', value: 'Лүн' },
  { parent: 'Төв аймаг', label: 'Мөнгөнморьт', value: 'Мөнгөнморьт' },
  { parent: 'Төв аймаг', label: 'Өндөрширээт', value: 'Өндөрширээт' },
  { parent: 'Төв аймаг', label: 'Сүмбэр', value: 'Сүмбэр' },
  { parent: 'Төв аймаг', label: 'Сэргэлэн', value: 'Сэргэлэн' },
  { parent: 'Төв аймаг', label: 'Угтаалцайдам', value: 'Угтаалцайдам' },
  { parent: 'Төв аймаг', label: 'Цээл', value: 'Цээл' },
  { parent: 'Төв аймаг', label: 'Эрдэнэ', value: 'Эрдэнэ' },
  { parent: 'Төв аймаг', label: 'Эрдэнэсант', value: 'Эрдэнэсант' },

  { parent: 'Увс аймаг', label: 'Улаангом', value: 'Улаангом' },
  { parent: 'Увс аймаг', label: 'Баруунтуруун', value: 'Баруунтуруун' },
  { parent: 'Увс аймаг', label: 'Бөхмөрөн', value: 'Бөхмөрөн' },
  { parent: 'Увс аймаг', label: 'Давст', value: 'Давст' },
  { parent: 'Увс аймаг', label: 'Завхан', value: 'Завхан' },
  { parent: 'Увс аймаг', label: 'Зүүнговь', value: 'Зүүнговь' },
  { parent: 'Увс аймаг', label: 'Зүүнхангай', value: 'Зүүнхангай' },
  { parent: 'Увс аймаг', label: 'Малчин', value: 'Малчин' },
  { parent: 'Увс аймаг', label: 'Наранбулаг', value: 'Наранбулаг' },
  { parent: 'Увс аймаг', label: 'Өлгий', value: 'Өлгий' },
  { parent: 'Увс аймаг', label: 'Өмнөговь', value: 'Өмнөговь' },
  { parent: 'Увс аймаг', label: 'Өндөрхангай', value: 'Өндөрхангай' },
  { parent: 'Увс аймаг', label: 'Сагил', value: 'Сагил' },
  { parent: 'Увс аймаг', label: 'Тариалан', value: 'Тариалан' },
  { parent: 'Увс аймаг', label: 'Түргэн', value: 'Түргэн' },
  { parent: 'Увс аймаг', label: 'Тэс', value: 'Тэс' },
  { parent: 'Увс аймаг', label: 'Ховд', value: 'Ховд' },
  { parent: 'Увс аймаг', label: 'Хяргас', value: 'Хяргас' },
  { parent: 'Увс аймаг', label: 'Цагаанхайрхан', value: 'Цагаанхайрхан' },

  { parent: 'Ховд аймаг', label: 'Ховд', value: 'Ховд' },
  { parent: 'Ховд аймаг', label: 'Алтай', value: 'Алтай' },
  { parent: 'Ховд аймаг', label: 'Булган', value: 'Булган' },
  { parent: 'Ховд аймаг', label: 'Буянт', value: 'Буянт' },
  { parent: 'Ховд аймаг', label: 'Дарви', value: 'Дарви' },
  { parent: 'Ховд аймаг', label: 'Дөргөн', value: 'Дөргөн' },
  { parent: 'Ховд аймаг', label: 'Дуут', value: 'Дуут' },
  { parent: 'Ховд аймаг', label: 'Жаргалант', value: 'Жаргалант' },
  { parent: 'Ховд аймаг', label: 'Зэрэг', value: 'Зэрэг' },
  { parent: 'Ховд аймаг', label: 'Манхан', value: 'Манхан' },
  { parent: 'Ховд аймаг', label: 'Мөнххайрхан', value: 'Мөнххайрхан' },
  { parent: 'Ховд аймаг', label: 'Мөст', value: 'Мөст' },
  { parent: 'Ховд аймаг', label: 'Мянгад', value: 'Мянгад' },
  { parent: 'Ховд аймаг', label: 'Үенч', value: 'Үенч' },
  { parent: 'Ховд аймаг', label: 'Цэцэг', value: 'Цэцэг' },
  { parent: 'Ховд аймаг', label: 'Чандмань', value: 'Чандмань' },
  { parent: 'Ховд аймаг', label: 'Эрдэнэбүрэн', value: 'Эрдэнэбүрэн' },

  { parent: 'Хөвсгөл аймаг', label: 'Мөрөн', value: 'Мөрөн' },
  { parent: 'Хөвсгөл аймаг', label: 'Алаг-Эрдэнэ', value: 'Алаг-Эрдэнэ' },
  { parent: 'Хөвсгөл аймаг', label: 'Арбулаг', value: 'Арбулаг' },
  { parent: 'Хөвсгөл аймаг', label: 'Баянзүрх', value: 'Баянзүрх' },
  { parent: 'Хөвсгөл аймаг', label: 'Бүрэнтогтох', value: 'Бүрэнтогтох' },
  { parent: 'Хөвсгөл аймаг', label: 'Галт', value: 'Галт' },
  { parent: 'Хөвсгөл аймаг', label: 'Жаргалант', value: 'Жаргалант' },
  { parent: 'Хөвсгөл аймаг', label: 'Их-Уул', value: 'Их-Уул' },
  { parent: 'Хөвсгөл аймаг', label: 'Рашаант', value: 'Рашаант' },
  { parent: 'Хөвсгөл аймаг', label: 'Рэнчинлхүмбэ', value: 'Рэнчинлхүмбэ' },
  { parent: 'Хөвсгөл аймаг', label: 'Тариалан', value: 'Тариалан' },
  { parent: 'Хөвсгөл аймаг', label: 'Тосонцэнгэл', value: 'Тосонцэнгэл' },
  { parent: 'Хөвсгөл аймаг', label: 'Төмөрбулаг', value: 'Төмөрбулаг' },
  { parent: 'Хөвсгөл аймаг', label: 'Түнэл', value: 'Түнэл' },
  { parent: 'Хөвсгөл аймаг', label: 'Улаан-Уул', value: 'Улаан-Уул' },
  { parent: 'Хөвсгөл аймаг', label: 'Ханх', value: 'Ханх' },
  { parent: 'Хөвсгөл аймаг', label: 'Хатгал', value: 'Хатгал' },
  { parent: 'Хөвсгөл аймаг', label: 'Цагааннуур', value: 'Цагааннуур' },
  { parent: 'Хөвсгөл аймаг', label: 'Цагаан-Уул', value: 'Цагаан-Уул' },
  { parent: 'Хөвсгөл аймаг', label: 'Цагаан-Үүр', value: 'Цагаан-Үүр' },
  { parent: 'Хөвсгөл аймаг', label: 'Цэцэрлэг', value: 'Цэцэрлэг' },
  { parent: 'Хөвсгөл аймаг', label: 'Чандмань-Өндөр', value: 'Чандмань-Өндөр' },
  { parent: 'Хөвсгөл аймаг', label: 'Шинэ-Идэр', value: 'Шинэ-Идэр' },
  { parent: 'Хөвсгөл аймаг', label: 'Эрдэнэбулган', value: 'Эрдэнэбулган' },

  { parent: 'Хэнтий аймаг', label: 'Чингис', value: 'Чингис' },
  { parent: 'Хэнтий аймаг', label: 'Батноров', value: 'Батноров' },
  { parent: 'Хэнтий аймаг', label: 'Батширээт', value: 'Батширээт' },
  { parent: 'Хэнтий аймаг', label: 'Баян-Адарга', value: 'Баян-Адарга' },
  { parent: 'Хэнтий аймаг', label: 'Баянмөнх', value: 'Баянмөнх' },
  { parent: 'Хэнтий аймаг', label: 'Баян-Овоо', value: 'Баян-Овоо' },
  { parent: 'Хэнтий аймаг', label: 'Баянхутаг', value: 'Баянхутаг' },
  { parent: 'Хэнтий аймаг', label: 'Биндэр', value: 'Биндэр' },
  { parent: 'Хэнтий аймаг', label: 'Бор-Өндөр', value: 'Бор-Өндөр' },
  { parent: 'Хэнтий аймаг', label: 'Галшар', value: 'Галшар' },
  { parent: 'Хэнтий аймаг', label: 'Дадал', value: 'Дадал' },
  { parent: 'Хэнтий аймаг', label: 'Дархан', value: 'Дархан' },
  { parent: 'Хэнтий аймаг', label: 'Дэлгэрхаан', value: 'Дэлгэрхаан' },
  { parent: 'Хэнтий аймаг', label: 'Жаргалтхаан', value: 'Жаргалтхаан' },
  { parent: 'Хэнтий аймаг', label: 'Мөрөн', value: 'Мөрөн' },
  { parent: 'Хэнтий аймаг', label: 'Норовлин', value: 'Норовлин' },
  { parent: 'Хэнтий аймаг', label: 'Өмнөдэлгэр', value: 'Өмнөдэлгэр' },
  { parent: 'Хэнтий аймаг', label: 'Хэрлэн', value: 'Хэрлэн' },
  { parent: 'Хэнтий аймаг', label: 'Цэнхэрмандал', value: 'Цэнхэрмандал' },
];

export const currencyList = [
  { label: 'Төгрөг (₮)', value: '₮' },
  { label: 'Dollar ($)', value: '$' }
]

export const topColors = [
  '#017aff',
  '#f34971',
  '#f5c900',
  '#39c0c8',
  '#6c47ff'
];

export const excelTypes = [
  // 'application/vnd.ms-excel',
  'application/msexcel',
  'application/x-msexcel',
  'application/x-ms-excel',
  'application/x-excel',
  'application/x-dos_ms_excel',
  'application/xls',
  'application/x-xls',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
];

export const subscriptions = [
  { amt: 10000, length: 'сар', text: 'Сараар нэг ажилтан', value: 0 },
  { amt: 100000, length: 'жил', text: 'Жилээр нэг ажилтан', value: 1 },
];

export const banks = [
  { label: 'Хаан банк', bank: 'ХААНБАНК', logo: 'haan', acct: 'MN48 0005 00 5011703186', name: 'МасуПОС ххк' },
  { label: 'Худалдаа хөгжлийн банк', bank: 'ХХБ', logo: 'tdb', acct: 'MN25 0004000 819006011', name: 'МасуПОС ххк' },
  // { label: 'Хас банк', bank: 'ХАСБАНК', logo: 'has', acct: '5005573920', name: 'МасуПОС ххк' },
  // { label: 'Голомт банк', bank: 'ГОЛОМТБАНК', logo: 'golomt', acct: '1605231423', name: 'МасуПОС ххк' },
];

export const types = [
  { label: "Бүх хэрэглэгч", value: "ALL" },
  { label: "Сонгосон хэрэглэгч", value: "MERCHANT" }
];

export const status = [
  { statusName: "Захиалганд байгаа", status: 0 },
  { statusName: "Захиалга биелсэн", status: 1 },
  { statusName: "Хүчингүй болсон захиалга", status: 9 }
];

export const siteSubscriptions = [
  { amt: 25000, length: 'MONTH', text: 'Сараар нэг салбар', value: 0, label: "25,000₮/салбар" },
  { amt: 250000, length: 'YEAR', text: 'Жилээр нэг салбар', value: 1, label: "250,000₮/салбар" },
  { amt: 0, length: 'TRIAL', text: '14 хоног үнэгүй', value: 2, label: "Туршилт хийх" },
];

export const siteSubscriptions1 = [
  { amt: 25000, length: 'MONTH', text: 'Сараар нэг салбар', value: 0, label: "25,000₮/салбар" },
  { amt: 250000, length: 'YEAR', text: 'Жилээр нэг салбар', value: 1, label: "250,000₮/салбар" },
];

export const subs = [
  { label: "Борлуулалт хийх", value: "0" },
  { label: "Нийлүүлэлт хийх", value: "1" }
];

export const week = [
  { label: "7 хоног", value: "7 хоног" },
  { label: "Ажлын өдөр", value: "Ажлын өдөр" },
  { label: "Сар", value: "Сар" },
  { label: "Өдөр", value: "Өдөр" }
];

export const calendar = [
  { label: "Даваа", value: 1},
  { label: "Мягмар", value: 2 },
  { label: "Лхагва", value: 3 },
  { label: "Пүрэв", value: 4 },
  { label: "Баасан", value: 5 },
  { label: "Бямба", value: 6 },
  { label: "Ням", value: 7 },
];

export const timeList1 = [
  { label: '00:00', value: '00:00'}, { label: '00:30', value: '00:30'}, { label: '01:00', value: '01:00'}, { label: '01:30', value: '01:30'},   
  { label: '02:00', value: '02:00'}, { label: '02:30', value: '02:30'}, { label: '03:00', value: '03:00'}, { label: '03:30', value: '03:30'},   
  { label: '04:00', value: '04:00'}, { label: '04:30', value: '04:30'}, { label: '05:00', value: '05:00'}, { label: '05:30', value: '05:30'},   
  { label: '06:00', value: '06:00'}, { label: '06:30', value: '06:30'}, { label: '07:00', value: '07:00'}, { label: '07:30', value: '07:30'},   
  { label: '08:00', value: '08:00'}, { label: '08:30', value: '08:30'}, { label: '09:00', value: '09:00'}, { label: '09:30', value: '09:30'},   
  { label: '10:00', value: '10:00'}, { label: '10:30', value: '10:30'}, { label: '11:00', value: '11:00'}, { label: '11:30', value: '11:30'},   
  { label: '12:00', value: '12:00'}, { label: '12:30', value: '12:30'}, { label: '13:00', value: '13:00'}, { label: '13:30', value: '13:30'},   
  { label: '14:00', value: '14:00'}, { label: '14:30', value: '14:30'}, { label: '15:00', value: '15:00'}, { label: '15:30', value: '15:30'},   
  { label: '16:00', value: '16:00'}, { label: '16:30', value: '16:30'}, { label: '17:00', value: '17:00'}, { label: '17:30', value: '17:30'},   
  { label: '18:00', value: '18:00'}, { label: '18:30', value: '18:30'}, { label: '19:00', value: '19:00'}, { label: '19:30', value: '19:30'},   
  { label: '20:00', value: '20:00'}, { label: '20:30', value: '20:30'}, { label: '21:00', value: '21:00'}, { label: '21:30', value: '21:30'},   
  { label: '22:00', value: '22:00'}, { label: '22:30', value: '22:30'}, { label: '23:00', value: '23:00'}, { label: '23:30', value: '23:30'},   
];

export const selectSubscription = [
  {value: 0, type: 'STANDARD', type1: 'PREMIUM', length: 'MONTH', amt: 50000, amt1: 100000, label: 'Сар', label1: 'сар'},
  {value: 2, type: 'STANDARD', type1: 'PREMIUM', length: '3MONTH', amt: 140000, amt1: 280000, label: '3 сар', label1: '3 сар'},
  {value: 3, type: 'STANDARD', type1: 'PREMIUM', length: '6MONTH', amt: 270000, amt1: 520000, label: '6 сар', label1: '6 сар'},
  {value: 1, type: 'STANDARD', type1: 'PREMIUM', length: 'YEAR', amt: 500000, amt1: 1000000, label: 'Жил', label1: 'жил'}
];

export const subContent = [
  { value: 0, label: 'Борлуулалтын Пос(Дэлгүүр)'}, 
  { value: 1, label: 'Борлуулалтын Пос(Ресторан)'}, 
  { value: 2, label: 'Түгээлтийн ПОС (Distribution)'}, 
  { value: 3, label: 'И-Баримт холболт'}, 
  { value: 4, label: 'Борлуулалтын тайлан, мэдээ'}, 
  { value: 5, label: 'Бараа сурталчлах самбар'}, 
  { value: 6, label: 'Барааны үлдэгдэл хөтлөх (FIFO)'}, 
  { value: 7, label: 'Ажилтан'}, 
  { value: 8, label: 'Loyalty app/ Цаг захиалга'}, 
  { value: 9, label: 'Loyalty app/ Voucher, coupon, discount'}, 
  { value: 10, label: 'Нэгдсэн захиалгын систем'}, 
  { value: 11, label: 'Санхүү (Accounting)'},
  { value: 11, label: 'Нэхэмжлэх (Invoicing)'},
  { value: 11, label: 'Integration / API'},
  { value: 11, label: 'Дэмжлэг (Support 24/7)'}
];

export const subContent1 = [
  { value: 0, label: 'Борлуулалтын Пос(Дэлгүүр)'}, 
  { value: 1, label: 'Борлуулалтын Пос(Ресторан)'}, 
  { value: 2, label: 'Түгээлтийн ПОС (Distribution)'}, 
  { value: 3, label: 'И-Баримт холболт'}, 
  { value: 4, label: 'Борлуулалтын тайлан, мэдээ'}, 
  { value: 5, label: 'Барааны үлдэгдэл хөтлөх (FIFO)'}, 
  { value: 6, label: 'Ажилтан'}, 
  { value: 7, label: 'Loyalty app/ Voucher, coupon, discount'}, 
  { value: 8, label: 'Нэгдсэн захиалгын систем'}
];